"""Stable domain enumerations."""

from enum import Enum


class SignalStatus(str, Enum):
    CREATED = "CREATED"
    IGNORED = "IGNORED"
    EXPIRED = "EXPIRED"
    CONFIRMED = "CONFIRMED"


class SignalType(str, Enum):
    CALL = "CALL"
    PUT = "PUT"
    STRADDLE = "STRADDLE"
    CALL_SPECIAL = "CALL_SPECIAL"
    PUT_SPECIAL = "PUT_SPECIAL"
    STRADDLE_SPECIAL = "STRADDLE_SPECIAL"


class TradeStatus(str, Enum):
    """Lifecycle states for active order execution and positions."""

    CREATED = "CREATED"
    CONFIRMED = "CONFIRMED"
    ENTRY_PENDING = "ENTRY_PENDING"
    ENTERED = "ENTERED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    EXIT_PENDING = "EXIT_PENDING"
    EXITED = "EXITED"
    REJECTED = "REJECTED"
    IGNORED = "IGNORED"
    EXPIRED = "EXPIRED"
    ERROR = "ERROR"


class RiskAction(str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"


class RiskRejectionReason(str, Enum):
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    MAX_DAILY_LOSS_EXCEEDED = "MAX_DAILY_LOSS_EXCEEDED"
    MAX_OPEN_POSITIONS_REACHED = "MAX_OPEN_POSITIONS_REACHED"
    MAX_UNDERLYING_EXPOSURE_EXCEEDED = "MAX_UNDERLYING_EXPOSURE_EXCEEDED"
    MAX_TRADE_NOTIONAL_EXCEEDED = "MAX_TRADE_NOTIONAL_EXCEEDED"
    SYMBOL_SESSION_LIMIT_REACHED = "SYMBOL_SESSION_LIMIT_REACHED"
    DUPLICATE_SIGNAL_LOCKED = "DUPLICATE_SIGNAL_LOCKED"
    MARKET_CLOSED = "MARKET_CLOSED"
    BROKER_UNHEALTHY = "BROKER_UNHEALTHY"
    SLIPPAGE_EXCEEDED = "SLIPPAGE_EXCEEDED"
    MANUAL_CONFIRMATION_REQUIRED = "MANUAL_CONFIRMATION_REQUIRED"
