"""Broker-neutral engine models."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Mapping

from .enums import SignalStatus, SignalType


@dataclass(frozen=True)
class Signal:
    """Trading signal generated by strategy evaluation."""

    id: str
    symbol: str
    case_number: int
    created_at: datetime
    status: SignalStatus = SignalStatus.CREATED
    signal_type: SignalType = SignalType.CALL
    underlying_price: float = 0.0
    pcr: float = 1.0
    strategy_version: str = "0.1.0"
    reason: str = ""
    indicators: Mapping[str, Any] = field(default_factory=dict)
